config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # get 'articles/index'
  # get('/articles', {to: 'articles#index'} )
  # get "/articles/new", to: "articles#new"
  # get "/articles/:id", to: "articles#destroy"
  resources :articles do
    resources :comments
  end
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    # include Visible
    
    VALID_STATUSES = ['public', 'private', 'archived']

    has_many:comments,dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    validates :status, inclusion: { in: VALID_STATUSES }
    def archived?
        status == 'archived'
      end
end

app/models/comment.rb
class Comment < ApplicationRecord
  # include Visible
  
  belongs_to :user
  belongs_to :article

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many:comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #refactoring to code prevent repeat
  # before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    # @ >> instance variable
    @articles = Article.all
  end
   # -----------------------------
  def show
    @article = Article.find(params[:id])
  end  
  # --------------------------------
  def new
    @article = Article.new
  end  
  # -----------------------------
  def create
    @article = Article.new(article_params)
    # @article.save
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
    # render plain: params
  end  
   # -----------------------------
   def edit
    @article = Article.find(params[:id])
  end  
   # -----------------------------
   def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end  
   # -----------------------------
   def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
    # @article = Article.find(params[:id])
    # redirect_to articles_path if @article.destroy
   end  
   # -----------------------------
  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
  # --------------------------------------------------
  #this method to repeat this line in all methods
  # def set_article
  #   @article = Article.find(params[:id])
  # end  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      comment = @article.comments.new(comment_params)
      comment.user_id = 2
      redirect_to article_path(@article) if comment.save
    end
    # -------------------------
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article), status: 303
    end
    # ---------------------------
    def show
    end  
    # ---------------------------
    private
    def comment_params
      params.require(:comment).permit(:body, :status)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article,data: {turbo:false} do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "New Article", new_article_path %>
<ul>
  <% @articles.each do |article| %>
  <% unless article.archived? %>
    <li>
      <%= article.title %> 
      <%= link_to 'Show', article %>
      <%= link_to "Edit", edit_article_path(article) %>
      <%= link_to "Destroy", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    
                  } %>      
    </li>
    
  <% end %>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Article</h1>
<h1><%= @article.title %></h1>
<p>Body : <%= @article.body %></p>
<p>Status : <%= @article.status %></p>
<hr/>


<h2>Comments</h2>
<%= render @article.comments %>
<hr/>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
                

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
    <strong>Commenter:</strong>
    <%= comment.user.first_name %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>
 <% end %> 

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <p>
  
    <%= form.submit %>
  </p>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= 'welcome ' + current_user.first_name if user_signed_in? %>
  <%= link_to('LogOut',destroy_user_session_path, data: {
    trubo_method: :delete
  }) if user_signed_in?%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>